name: Wireguard SSH deploy (testing)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Determine branch name
      run: echo Github Refs - ${GITHUB_REF}\nRunning on branch ${GITHUB_REF##*/}

    - name: Install wireguard
      run: sudo apt-get install wireguard

    - name: Create wireguard tunnel configuration
      run: |
        sed -i -e "s@{{PLACEHOLDER_WIREGUARD_PRIVATE_KEY}}@${{ secrets.WIREGUARD_PRIVATE_KEY }}@" $GITHUB_WORKSPACE/.github/workflows/deploy-tunnel.conf
        sed -i -e "s@{{PLACEHOLDER_WIREGUARD_SERVER_PUBLIC_KEY}}@${{ secrets.WIREGUARD_SERVER_PUBLIC_KEY }}@" $GITHUB_WORKSPACE/.github/workflows/deploy-tunnel.conf
        sed -i -e "s@{{PLACEHOLDER_WIREGUARD_SERVER_ENDPOINT}}@${{ secrets.WIREGUARD_SERVER_ENDPOINT }}@" $GITHUB_WORKSPACE/.github/workflows/deploy-tunnel.conf
        sudo cp $GITHUB_WORKSPACE/.github/workflows/deploy-tunnel.conf /etc/wireguard/tunnel.conf
    - name: Prepare ssh key for remote login
      run: |
        mkdir ~/.ssh/
        echo "${{ secrets.SSH_SERVER_DEPLOY_SECRET }}" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Establish tunnel
      run: wg-quick up tunnel
    - name: Deploy to test
      run: |
        ssh -o StrictHostKeyChecking=no starship@${{ secrets.TARGET_SERVER_LOCAL_IP }} mkdir -p /opt/starship-flight-updates/test/data_sources
        scp -o StrictHostKeyChecking=no $GITHUB_WORKSPACE/*.py starship@${{ secrets.TARGET_SERVER_LOCAL_IP }}:~/test/
        scp -o StrictHostKeyChecking=no $GITHUB_WORKSPACE/data_sources/*.py starship@${{ secrets.TARGET_SERVER_LOCAL_IP }}:~/test/data_sources/
        scp -o StrictHostKeyChecking=no $GITHUB_WORKSPACE/.env.default starship@${{ secrets.TARGET_SERVER_LOCAL_IP }}:~/test/
        ssh -o StrictHostKeyChecking=no starship@${{ secrets.TARGET_SERVER_LOCAL_IP }} cat /opt/starship-flight-updates/test/.env | sed -r "s/BRANCH=([^\"\n]+)/BRANCH=${GITHUB_REF##*/}/" | tee /opt/starship-flight-updates/test/.env
    - name: Restart the service
      run: ssh -o StrictHostKeyChecking=no starship@${{ secrets.TARGET_SERVER_LOCAL_IP }} systemctl --user restart starship-flight-updates-testing
    - name: Close tunnel
      run: wg-quick down tunnel